library(plotthis)
library(plotly)

# BarPlot
data(iris)
p1 <- BarPlot(iris, x = "Species", y = "Sepal.Length", theme = "theme_this")
fig1 <- ggplotly(p1)
cat("=== BarPlot xaxis gridcolor ===\n")
print(fig1$x$layout$xaxis$gridcolor)
cat("=== BarPlot yaxis gridcolor ===\n")
print(fig1$x$layout$yaxis$gridcolor)
cat("=== BarPlot xaxis showgrid ===\n")
print(fig1$x$layout$xaxis$showgrid)
cat("=== BarPlot yaxis showgrid ===\n")
print(fig1$x$layout$yaxis$showgrid)

# ViolinPlot
p2 <- ViolinPlot(iris, x = "Species", y = "Sepal.Length", theme = "theme_this")
fig2 <- ggplotly(p2)
cat("=== ViolinPlot xaxis gridcolor ===\n")
print(fig2$x$layout$xaxis$gridcolor)
cat("=== ViolinPlot yaxis gridcolor ===\n")
print(fig2$x$layout$yaxis$gridcolor)
cat("=== ViolinPlot xaxis showgrid ===\n")
print(fig2$x$layout$xaxis$showgrid)
cat("=== ViolinPlot yaxis showgrid ===\n")
print(fig2$x$layout$yaxis$showgrid)

# DensityPlot
p3 <- DensityPlot(iris, x = "Sepal.Length", theme = "theme_this")
fig3 <- ggplotly(p3)
cat("=== DensityPlot xaxis gridcolor ===\n")
print(fig3$x$layout$xaxis$gridcolor)
cat("=== DensityPlot yaxis gridcolor ===\n")
print(fig3$x$layout$yaxis$gridcolor)
cat("=== DensityPlot xaxis showgrid ===\n")
print(fig3$x$layout$xaxis$showgrid)
cat("=== DensityPlot yaxis showgrid ===\n")
print(fig3$x$layout$yaxis$showgrid)
