library(shinytest2)

test_that("{shinytest2} recording: test_areaPlot", {
  local_app_support(test_path("../../inst/apps/test_areaPlot"))
  app <- AppDriver$new(test_path("../../inst/apps/test_areaPlot"), name = "test_areaPlot", 
      seed = 7, height = 958, width = 1619)
  app$expect_values()
  app$set_inputs(`mtcars-y.data` = "wt")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-auto.update` = TRUE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-download.type` = "svg")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-AreaPlotTabsetPanel` = "Facet")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-AreaPlotTabsetPanel` = "Data")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-AreaPlotTabsetPanel` = "Facet")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-facet.by` = "gear")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-facet.scale` = "free")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-split.by` = "gear")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-facet.by.row` = FALSE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-design` = "NUL")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-design` = "100")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-design` = "100\n20")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-design` = "100\n200")
  app$wait_for_idle(800)
  app$expect_values()
  app$click("mtcars-reset")
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-auto.update` = FALSE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-AreaPlotTabsetPanel` = "Aesthetic")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-auto.update` = TRUE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-palette` = "Dark2")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-palette.colours` = "#66A61E")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-palette.colours` = c("#66A61E", "#7570B3"))
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-palette.colours` = c("#66A61E", "#7570B3", "#D95F02"))
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-theme` = "theme_light")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-alpha` = character(0))
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-alpha` = 0)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-alpha` = 0.4)
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-AreaPlotTabsetPanel` = "Labels")
  app$wait_for_idle(800)
  app$click("mtcars-reset")
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-font.type` = "Droid Sans")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 17)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 18)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 19)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 20)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 21)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 22)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 23)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 24)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 25)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 26)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 27)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 28)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 29)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 30)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 31)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 32)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 33)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 34)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 29)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 30)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 31)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 32)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-text.colour` = "#E81515")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-AreaPlotTabsetPanel` = "Axes")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.mirror` = FALSE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.showline` = FALSE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-auto.update` = FALSE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.linecolor` = "#CF2121")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickfont.color` = "#F52C2C")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickfont.family` = "Droid Sans")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 15)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 30)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 45)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 60)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 75)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 90)
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 105)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 120)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 135)
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.y` = -15)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.y` = 0)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.y` = 15)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.y` = 30)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.y` = 45)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.y` = 60)
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.ticks` = "inside")
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickcolor` = "#EB3636")
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.ticklen` = 6)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.ticklen` = 7)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.ticklen` = 8)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.ticklen` = 9)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.ticklen` = 10)
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickwidth` = 1.1)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickwidth` = 1.2)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickwidth` = 1.3)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickwidth` = 1.4)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickwidth` = 1.5)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickwidth` = 3.5)
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickfont.family` = "Droid Sans Mono")
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$click("mtcars-reset")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-text.colour` = "#000000")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.linecolor` = "#000000")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickfont.color` = "#000000")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickcolor` = "#000000")
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$expect_values()
})
