library(shinytest2)

test_that("{shinytest2} recording: test_piePlot", {
  local_app_support(test_path("../../inst/apps/test_piePlot"))
  app <- AppDriver$new(test_path("../../inst/apps/test_piePlot"), name = "test_piePlot", 
      seed = 7, height = 958, width = 1619)
  app$set_inputs(`mtcars-hole` = 0.28)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-hole` = 0)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-rotation` = 175)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-rotation` = 0)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-sort.slices` = FALSE)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-direction` = "clockwise")
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-auto.update` = TRUE)
  app$set_inputs(`mtcars-rotation` = 15)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-rotation` = 125)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-rotation` = 0)
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-auto.update` = FALSE)
  app$set_inputs(`mtcars-piePlotTabsetPanel` = "Colors")
  app$set_inputs(`mtcars-slice.colors` = c("4", "#e69f00", "6", "#56b4e9", "8", "#009e73"))
  app$set_inputs(`mtcars-slice.colors-palette` = "dittoColors")
  app$set_inputs(`mtcars-slice.line.color` = "#F52020")
  app$set_inputs(`mtcars-auto.update` = TRUE)
  app$set_inputs(`mtcars-slice.colors-palette` = "inferno")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-slice.colors-palette` = "Paired")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-slice.colors` = c("4", "#ffff99", "6", "#56b4e9", "8", "#009e73"))
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-slice.colors` = c("4", "#ffff99", "6", "#33a02c", "8", "#009e73"))
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-slice.colors` = c("4", "#ffff99", "6", "#33a02c", "8", "#ff7f00"))
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-slice.line.width` = 0.5)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-slice.line.width` = 1)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-slice.line.width` = 1.5)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-slice.line.width` = 2)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-slice.line.width` = 2.5)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-slice.line.width` = 3)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-slice.line.width` = 3.5)
  app$wait_for_idle(800)
  app$click("mtcars-reset")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-slice.line.color` = "#FFFFFF")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-piePlotTabsetPanel` = "Labels & Text")
  app$set_inputs(`mtcars-auto.update` = FALSE)
  app$set_inputs(`mtcars-textinfo` = c("label", "percent", "value"))
  app$set_inputs(`mtcars-textposition` = "inside")
  app$set_inputs(`mtcars-auto.update` = TRUE)
  app$set_inputs(`mtcars-textposition` = "outside")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-textposition` = "none")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-textposition` = "auto")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-insidetextorientation` = "tangential")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-text.font.size` = 13)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-text.font.size` = 14)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-text.font.size` = 15)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-text.font.size` = 16)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-text.font.size` = 17)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-text.font.size` = 18)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-text.font.family` = "Droid Sans")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-text.font.color` = "#F50505")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-download.type` = "svg")
  app$wait_for_idle(800)
  app$expect_values()
  app$click("mtcars-reset")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-text.font.color` = "#000000")
  app$set_inputs(`mtcars-auto.update` = FALSE)
  app$set_inputs(`mtcars-piePlotTabsetPanel` = "Title & Legend")
  app$set_inputs(`mtcars-title.x` = 0.78)
  app$set_inputs(`mtcars-auto.update` = TRUE)
  app$set_inputs(`mtcars-title.x` = 0.87)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.x` = 0.26)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-auto.update` = FALSE)
  app$set_inputs(`mtcars-auto.update` = TRUE)
  app$set_inputs(`mtcars-title.x` = 0.77)
  app$wait_for_idle(800)
  app$click("mtcars-reset")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.x` = 0)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.x` = 0.17)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.x` = 0.42)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.x` = 0.62)
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$expect_values()
  app$click("mtcars-reset")
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 29)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 30)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 31)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 32)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 33)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 34)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 35)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 36)
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-title.font.family` = "Droid Sans")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-title.font.color` = "#E81717")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.family` = "Droid Sans")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.family` = "Gravitas One")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.color` = "#C91414")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 13)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 14)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 15)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 16)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 17)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 18)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 19)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 20)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 21)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 22)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 23)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.orientation` = "v")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 22)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 21)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 20)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 19)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 18)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 1)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 2)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 3)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 4)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 5)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 13)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.size` = 14)
  app$wait_for_idle(800)
  app$expect_values()
  app$click("mtcars-reset")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.color` = "#000000")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-legend.font.color` = "#000000")
  app$wait_for_idle(800)
  app$expect_values()
})
