library(shinytest2)

test_that("{shinytest2} recording: test_barPlot", {
  local_app_support(test_path("../../inst/apps/test_barPlot"))
  app <- AppDriver$new(test_path("../../inst/apps/test_barPlot"), name = "test_barPlot", 
      seed = 7, height = 958, width = 1619)
  app$set_inputs(`mtcars-y.data` = "hp")
  app$wait_for_idle(800)
  app$click("mtcars-update")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-auto.update` = TRUE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.data` = "qsec")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-flip` = TRUE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-flip` = FALSE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.max` = 28)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.max` = 29)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.max` = 31)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.max` = 32)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.max` = 34)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.max` = 35)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.max` = 36)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.max` = 37)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.min` = 15)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.min` = 17)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.min` = 18)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.min` = 19)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.min` = 20)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-y.min` = 21)
  app$wait_for_idle(800)
  app$expect_values()
  app$click("mtcars-reset")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-auto.update` = FALSE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-download.type` = "svg")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-auto.update` = TRUE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-BarPlotTabsetPanel` = "Grouping")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-BarPlotTabsetPanel` = "Data")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-BarPlotTabsetPanel` = "Grouping")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-group.by` = "vs")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-group.by` = "gear")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-facet.by` = "vs")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-facet.scale` = "free")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-facet.by.row` = FALSE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-split.by` = "vs")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-BarPlotTabsetPanel` = "Aesthetic")
  app$wait_for_idle(800)
  app$click("mtcars-reset")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-palette` = "Pastel1")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-palette.colours` = "#B3CDE3")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-palette.colours` = c("#B3CDE3", "#E5D8BD"))
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-palette.colours` = c("#B3CDE3", "#E5D8BD", "#DECBE4"))
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-background.colour` = TRUE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-background.palette` = "Paired")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-background.alpha` = 1)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-theme` = "theme_minimal")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-alpha` = 0.4)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-width` = 1)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-width` = 2)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-width` = 3)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-expand` = "1,")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-expand` = "1,2")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-expand` = "1,2,4")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-BarPlotTabsetPanel` = "Line")
  app$wait_for_idle(800)
  app$click("mtcars-reset")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-add.line` = 20)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-line.colour` = "#F51313")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-line.type` = 2)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-line.type` = 3)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-line.type` = 4)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-line.width` = 1)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-line.width` = 2)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-line.width` = 3)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-line.width` = 4)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-line.width` = 5)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-line.name` = "Hello")
  app$wait_for_idle(800)
  app$expect_values()
  app$click("mtcars-reset")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-line.colour` = "#000000")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-BarPlotTabsetPanel` = "Labels")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-font.type` = "Courier New")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 19)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 20)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 21)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 22)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 23)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 24)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.font.size` = 25)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 29)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 31)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 32)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 33)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-title.font.size` = 34)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-text.colour` = "#E63333")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-download.type` = "svg")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-BarPlotTabsetPanel` = "Axes")
  app$wait_for_idle(800)
  app$expect_values()
  app$set_inputs(`mtcars-axis.linecolor` = "#D10F0F")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-auto.update` = FALSE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-auto.update` = TRUE)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickfont.color` = "#BD2C2C")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickcolor` = "#D11717")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.ticklen` = 6)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.ticklen` = 7)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.ticklen` = 8)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.ticklen` = 9)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.ticks` = "inside")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.y` = 15)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.y` = 30)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.y` = 45)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickfont.family` = "Courier New")
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 15)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 30)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 45)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickangle.x` = 60)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickfont.size` = 13)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickfont.size` = 14)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickfont.size` = 15)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-axis.tickfont.size` = 16)
  app$wait_for_idle(800)
  app$set_inputs(`mtcars-auto.update` = FALSE)
  app$wait_for_idle(800)
  app$expect_values()
})
